### ISSUE TITLE
IsEnabledSameEventMultiGroup有问题

### ISSUE THREAD

**Issue by ghnan** [tanyongzheng/AbpvNext.EventBus.Cap#1]
![image](https://user-images.githubusercontent.com/7714688/149073854-e07e9ef1-5934-45ed-9dcf-1b8189e8cab5.png)
如Domes中OrderService服务中，启用IsEnabledSameEventMultiGroup，并加入多个UpdateUserAddress事件，在消息队列中并不会创建对应的分组数。

**Comment by tanyongzheng** [comment]
感谢提出该问题，bug已修复
